title: UvA Data Science
description: Data Science Course at the University of Amsterdam
theme: just-the-docs

url: https://multix-amsterdam.github.io/data-science-book-uva

aux_links:
  GitHub: https://github.com/MultiX-Amsterdam/data-science-book-uva
